--Họ và tên: Trần Thế Tường
--Mã số sinh viên: 39157
-- cau 1
create PROCEDURE THEMMOINHANVIEN
AS
BEGIN
    INSERT INTO nhanvien(manv, hoten, ngaysinh, phai, quequan, sodt, mapb, macv)
	VALUES('nv11', N'Nhân viên 11', '2002-01-06', 1, N'Nam Định', N'0915662495', 'pb05', 'cv05');
END

exec THEMMOINHANVIEN;

-- cau 2
create PROCEDURE THEMMOINHANVIENVAOHESOLUONG
AS
BEGIN
    INSERT INTO hesoluong(thang, hsl, manv)
	VALUES(1, 1.5, 'nv11');
END

exec THEMMOINHANVIENVAOHESOLUONG;

-- cau 3
create PROCEDURE HIENTHIDANHSACHNHANVIENTHEOMACVVAMAPB
@mapb varchar(20), @macv varchar(20)
AS
BEGIN
    SELECT * FROM nhanvien where mapb = @mapb and macv = @macv
END

exec HIENTHIDANHSACHNHANVIENTHEOMACVVAMAPB @mapb='pb01', @macv='cv01'

-- cau 4
ALTER PROCEDURE THONGKESONHANVIENCOHSL
@HSL FLOAT
AS BEGIN
DECLARE @SOLUONGNHANVIEN INT;
	SELECT  @SOLUONGNHANVIEN = COUNT(distinct manv)  
	FROM  HESOLUONG 
	WHERE HESOLUONG.HSL>=@HSL
PRINT 'SO LUONG NHAN VIEN >=  '+CAST(@HSL AS VARCHAR(10)) +' LA : ' + CAST(@SOLUONGNHANVIEN AS VARCHAR(10));
END;

exec THONGKESONHANVIENCOHSL 3.0

-- CAU 5 TAO PROCEDURE CO THAM SO DAU RA LA SO NHAN VIEN CUA MOI PHONG BAN
CREATE PROCEDURE THAMSODAURADEMSONHANVIENMOIPHONGBAN
@SONVCUAMOIPHONGBAN INT OUTPUT,
@MAPB VARCHAR(10)

AS
BEGIN
    SELECT  @SONVCUAMOIPHONGBAN = COUNT(NHANVIEN.MANV)
    FROM nhanvien
	WHERE nhanvien.MAPB=@MAPB
    GROUP BY nhanvien.MAPB;
END;

DECLARE @DepartmentCount INT;
EXEC THAMSODAURADEMSONHANVIENMOIPHONGBAN @DepartmentCount OUTPUT, 'pb01';
SELECT @DepartmentCount AS THAMSODAURADEMSONHANVIENMOIPHONGBAN;

-- cau 6
ALTER PROCEDURE THAMSODAURATONGLUONGCUAMOITHANG
    @TONGLUONG FLOAT OUTPUT,
	@thang int
AS
BEGIN
    SELECT  @TONGLUONG = SUM(hsl * 1890000 * hscv)
    FROM nhanvien,hesoluong, chucvu
	WHERE nhanvien.manv = hesoluong.manv and
	chucvu.macv = nhanvien.macv and
	thang = @thang
END;

DECLARE @MONTH INT;
EXEC THAMSODAURATONGLUONGCUAMOITHANG @MONTH OUTPUT, 1
SELECT @MONTH AS SOLUONGTHEOTHANG;

-- CAU 7 TAO PROCEDURE CO THAM SO DAU RA THONG KE SO NHAN VIEN CO HSCV >=X
CREATE PROCEDURE SONHANVIENTHEOHSCV
@HSCV FLOAT,
@SOLUONGNHANVIENVIEN INT OUTPUT
AS BEGIN 
SELECT @SOLUONGNHANVIENVIEN =COUNT(NHANVIEN.MANV)
FROM NHANVIEN, CHUCVU WHERE NHANVIEN.MACV=CHUCVU.MACV AND CHUCVU.HSCV>=@HSCV
END;

DECLARE @TONGNHANVIEN INT;
EXEC SONHANVIENTHEOHSCV 1.5, @TONGNHANVIEN OUTPUT;
SELECT @TONGNHANVIEN AS TONGSONHANVIENTHEOHESOCHUCVU;

















