-- cau 1
CREATE FUNCTION SOMH_HOADON (@MAHD VARCHAR(5))
RETURNS INT
AS
BEGIN
    DECLARE @SOLUONGMH INT

    SELECT @SOLUONGMH = COUNT(*)
    FROM CHITIET
    WHERE mahd = @MAHD

    RETURN @SOLUONGMH
END

SELECT dbo.SOMH_HOADON('hd01') AS SOLUONGMH;


-- cau 2
ALTER FUNCTION HIENTHI_DANHSACH_MH_HOADON (@MAHD VARCHAR(5))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM chitiet
    WHERE chitiet.mahd = @MAHD
);


SELECT * FROM dbo.HIENTHI_DANHSACH_MH_HOADON('hd01') AS DSMATHANG;

-- cau 3
ALTER FUNCTION SOLUONG_HOADON_TUNGLOAI (@loaihd NVARCHAR(55))
RETURNS INT
AS
BEGIN
    DECLARE @SOLUONGHD INT
    SELECT @SOLUONGHD = COUNT(*)
    FROM hoadon
    WHERE loaihd = @loaihd
    RETURN @SOLUONGHD
END

DECLARE @SL INT;
SET @SL = dbo.SOLUONG_HOADON_TUNGLOAI(N'Bán');
PRINT (N'SL HOA DON THEO LOAI: ' + CONVERT(VARCHAR(5), @SL));
SET @SL = dbo.SOLUONG_HOADON_TUNGLOAI(N'Mua');
PRINT (N'SL HOA DON THEO LOAI: ' + CONVERT(VARCHAR(5), @SL));

-- cau 4
CREATE FUNCTION HIENTHI_DANHSACH_HD_KH (@MAKH VARCHAR(5))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM hoadon
    WHERE hoadon.makh = @MAKH
);


SELECT * FROM dbo.HIENTHI_DANHSACH_HD_KH('kh01');

--cau 5
ALTER FUNCTION SOHOADON_KHACHHANG (@MAKH VARCHAR(5))
RETURNS INT
AS
BEGIN
    DECLARE @SOLUONGHD INT
    SELECT @SOLUONGHD = COUNT(*)
    FROM hoadon
    WHERE makh = @MAKH

    RETURN @SOLUONGHD
END

SELECT dbo.SOHOADON_KHACHHANG('kh01') AS SOLUONGHDKHACHHANG;
SELECT dbo.SOHOADON_KHACHHANG('kh02') AS SOLUONGHDKHACHHANG;
SELECT dbo.SOHOADON_KHACHHANG('kh03') AS SOLUONGHDKHACHHANG;


select * from khachhang
select * from hoadon
select * from dmhang
select * from nhacungcap
select * from chitiet
select * from dathang